server {
    listen 80;
    server_name localhost;

    root /app;
    sendfile off;
    index index.php index.html;

    client_max_body_size 10M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	fastcgi_param DB_HOST mariadb;
	fastcgi_param DB_PORT 3306;
	fastcgi_param DB_USER root;
	fastcgi_param DB_PASSWORD root;
	fastcgi_param DB_NAME vladyslavshusharin;

    }
}
